### ISSUE TITLE
Error on Safari and Firefox: "ReferenceError: Can't find variable: TouchEvent"

### ISSUE THREAD

**Issue by angelomotta** [piotrdz/ng5-slider#4] opened 2018-05-18 15:46 UTC
Error in Safari and Firefox:

"ReferenceError: Can't find variable: TouchEvent"

**Comment by angelomotta** [comment] 2018-05-18 16:26
Trying to pull a quick fix, but I have no access to Pull Request.

**Comment by piotrdz** [comment] 2018-05-19 08:02
Thanks for reporting this issue. Could you provide more details of when it happens / what exactly isn't working?

I checked the Plunker example page on Firefox 60.0 and from what I can see, it seems to be working fine. I don't have access to any Mac machine at the moment, so I can't check Safari.

**Comment by piotrdz** [comment] 2018-05-19 08:05
Also, you should be able to create a pull request by first forking the repository, making the fix in your fork and then creating a pull request back to the main repository.

**Comment by angelomotta** [comment] 2018-05-20 10:57
The bug happens when I try slider the component.

I am using:
MacOS 10.12.6 
Firefox 59.0.2 (64-bit)
Safari Version 11.1

I will try again the pull request.

**Comment by piotrdz** [comment] 2018-05-23 10:58
I managed to reproduce this issue by using an older version of Firefox (36.0). I created my own fix for this which seems to work. Please let me know if this also fixes it on your end @angelomotta.

**Comment by piotrdz** [comment] 2018-05-26 06:35
I tested my fix also on Safari 11 on Mac OSX 10.13 using http://crossbrowsertesting.com/ and it seems to work fine.

I think this is fixed now, so I'll close this issue. If there are any more problems, it can be reopened.

**Closed by piotrdz** 2018-05-26 06:35 UTC
